### ISSUE TITLE
How can i use capslock to switch lang?

### ISSUE THREAD

**Issue by seriiserii825** [porras/i3-keyboard-layout#4]
Hi, i prefer to use capslock for switch, but i think, that with this key will be problems. 
Do you know how to resolve this?

**Comment by porras** [comment]
Hi! I haven't done this myself but, while you can't directly map capslock in i3, you can _probably_ use setxkbmap to map capslock to something else, and then map that something else to this script.

I'm closing this issue, since it's not specific to this script but to any mapping in i3, but if you find the solution please consider posting it here, for the benefit of anyone searching for this in the future, and ending up here :smiley_cat:
