### ISSUE TITLE
Something simpler, please

### ISSUE THREAD

**Issue by ersi-dnd** [porras/i3-keyboard-layout#5]
The idea to display keyboard layout in i3status bar is very good (and frankly should be implemented in i3status conf itself), but all you really need is setxkbmap, which probably comes in every Linux. Specifically, it would be great to somehow display the output of 

  setxkbmap -query | awk '/layout/{print $2}'

This output should somehow go in i3status bar. I have not found a way to include this in i3status. It is very puzzling to me that i3wm developers, otherwise extremely conscious of utf8 stuff and such, do not allow a simple output like this in i3status.

**Comment by apiraino** [comment]
@ersi-dnd many of us i3 users have developed custom-tailored solutions for little problems like this.

While I find the solution in this repo better engineered, you might want to have a look at an alternate, [simpler approach I wrote](https://gitlab.com/apiraino/dotfiles/blob/master/i3/i3kblayout.sh). I use [py3status](https://github.com/ultrabug/py3status), therefore I don't need to kill i3 to see the changes.

(sorry for the slightly off-topic comment)

**Comment by porras** [comment]
@ersi-dnd agreed! that is exactly what this script does (with grep instead of awk but you get it), the rest is just simple glue to work around the limitation in i3status that you mention.

I'm closing the issue, since this would be an issue in i3status, not here (maybe you want to consider reporting it there). I think though, that their approach is not to include features that can be done with a couple of lines of shell script, and I don't necessarily disagree, since that philosophy seems to be working well for the i3 project, which we all love :smile_cat: 

Thank you for the feedback, in any case.
